cardbox/urls.py
# django-cardbox -- A collection manager for Magic: The Gathering
# Copyright (C) 2016 Benedikt Rascher-Friesenhausen
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.conf.urls import url

from . import views


app_name = 'cardbox'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^cards/$', views.cards, name='cards'),
    url(r'^card/(?P<card_id>[0-9]+)/$', views.card, name='card'),
    url(r'^collection/new/$', views.edit_collection, name='new_collection'),
    url(r'^collection/edit/(?P<collection_id>[0-9]+)/$',
        views.edit_collection, name='edit_collection'),
    url(r'^collection/delete/(?P<collection_id>[0-9]+)/$',
        views.delete_collection, name='delete_collection'),
    url(r'^collection/(?P<collection_id>[0-9]+)/$',
        views.collection, name='collection'),
    url(r'^collection/(?P<collection_id>[0-9]+)/add$',
        views.add_collection_entry, name='add_collection_entry'),
    url(r'^ajax/collectionentries/(?P<collection_id>[0-9]+)/update$',
        views.update_collection_entries, name='update_collection_entries'),
    url(r'^collection/(?P<collection_id>[0-9]+)/card/(?P<card_id>[0-9]+)/$',
        views.collection_card, name='collection_card'),
]

cardboxsite/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/doc', include('django.contrib.admindocs.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cardbox.urls')),
]

cardbox/views.py
# django-cardbox -- A collection manager for Magic: The Gathering
# Copyright (C) 2016 Benedikt Rascher-Friesenhausen
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import PermissionDenied
from django.core.urlresolvers import reverse
from django.db.models import F
from django.db.utils import IntegrityError
from django.http import Http404, HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, get_list_or_404, render
from django.utils import timezone
from django_ajax.decorators import ajax
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

from cardbox.models import (
    Set,
    Card,
    CardEdition,
    Collection,
    CollectionEntry,
)

from cardbox.utils.auth import (
    can_edit_collection,
    can_view_collection,
)

from cardbox.utils.filters import (
    filter_cards_by_name,
    filter_cards_by_types,
    filter_cards_by_rules,
    filter_cards_by_flavour,
    filter_cards_by_mana,
    filter_cards_by_power,
    filter_cards_by_toughness,
    filter_cards_by_loyalty,
    filter_cards_by_cmc,
    filter_cards_by_artist,
    filter_cards_by_rarity,
    filter_cards_by_format,
    filter_cards_by_multi_type,
    filter_cards_by_blocks_sets,
)


def _update_many_to_many_field(entries, m2m_manager):
    """Update the entries for a ManyToManyField.

    :param list entries: The entries the ManyToManyField should have
        after the update.

    :param m2m_manager: The model manager.

    """
    for entry in m2m_manager.all():
        if entry not in entries:
            m2m_manager.remove(entry)
    for entry in entries:
        m2m_manager.add(entry)


def _filter_cards(request, queryset):
    """Filter a list of cards.

    :param request: A request object whose POST dictionary contains
        card filters.

    :param queryset: The query set for the cards.

    :returns: A query set for the filtered cards.

    """
    filtered = queryset
    errors = {}
    fstr_name = request.GET.get('fna', '')
    fstr_types = request.GET.get('fty', '')
    fstr_rules = request.GET.get('fru', '')
    fstr_flavour = request.GET.get('ffl', '')
    fstr_mana = request.GET.get('fma', '')
    fstr_power = request.GET.get('fpo', '')
    fstr_toughness = request.GET.get('fto', '')
    fstr_loyalty = request.GET.get('flo', '')
    fstr_cmc = request.GET.get('fcm', '')
    fstr_artist = request.GET.get('far', '')
    fstr_rarity = request.GET.get('fra', '')
    fstr_format = request.GET.get('ffo', '')
    fstr_multi_type = request.GET.get('fmt', '')
    fstr_block_sets = request.GET.get('fbs', '')

    filtered, errors['fna'] = filter_cards_by_name(filtered, fstr_name)
    filtered, errors['fty'] = filter_cards_by_types(filtered, fstr_types)
    filtered, errors['fru'] = filter_cards_by_rules(filtered, fstr_rules)
    filtered, errors['ffl'] = filter_cards_by_flavour(filtered, fstr_flavour)
    filtered, errors['fma'] = filter_cards_by_mana(filtered, fstr_mana)
    filtered, errors['fpo'] = filter_cards_by_power(filtered, fstr_power)
    filtered, errors['fto'] = filter_cards_by_toughness(filtered, fstr_toughness)
    filtered, errors['flo'] = filter_cards_by_loyalty(filtered, fstr_loyalty)
    filtered, errors['fcm'] = filter_cards_by_cmc(filtered, fstr_cmc)
    filtered, errors['far'] = filter_cards_by_artist(filtered, fstr_artist)
    filtered, errors['fra'] = filter_cards_by_rarity(filtered, fstr_rarity)
    filtered, errors['ffo'] = filter_cards_by_format(filtered, fstr_format)
    filtered, errors['fmt'] = filter_cards_by_multi_type(filtered, fstr_multi_type)
    filtered, errors['fbs'] = filter_cards_by_blocks_sets(filtered, fstr_block_sets)

    return filtered.distinct(), errors


def index(request):
    card_list = Card.objects.all()
    paginator = Paginator(card_list, 50, request=request)

    page = request.GET.get('page', 1)
    try:
        cards = paginator.page(page)
    except PageNotAnInteger:
        cards = paginator.page(1)
    except EmptyPage:
        cards = paginator.page(paginator.num_pages)

    return render(request, 'cardbox/index.html', {
        'cards': cards,
    })


def login_view(request):
    data = {'next': request.GET.get('next', '')}
    try:
        username = request.POST['username']
        password = request.POST['password']
    except KeyError:
        return render(request, 'cardbox/login.html', data)

    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            next_url = request.POST.get('next', '')
            if next_url == '':
                return HttpResponseRedirect(reverse('cardbox:index'))
            return HttpResponseRedirect(next_url)
        else:
            messages.add_message(request, messages.WARNING, 'User not active!')
            return render(request, 'cardbox/login.html', data)
    else:
        messages.add_message(request, messages.WARNING, 'User not found!')
        return render(request, 'cardbox/login.html', data)


def logout_view(request):
    logout(request)
    messages.add_message(request, messages.SUCCESS,
                         "You were successfully logged out.")
    return HttpResponseRedirect(reverse('cardbox:index'))


def cards(request):
    layout = request.GET.get('layout', 'list')
    if layout not in ['list', 'grid']:
        layout = 'list'

    card_list, ferrors = _filter_cards(request, Card.objects.all())
    paginator = Paginator(card_list, 30, request=request)

    page = request.GET.get('page', 1)
    try:
        cards = paginator.page(page)
    except PageNotAnInteger:
        cards = paginator.page(1)
    except EmptyPage:
        cards = paginator.page(paginator.num_pages)

    return render(request, 'cardbox/cards.html', {
        'cards': cards,
        'get': request.GET,
        'layout': layout,
        'ferrors': ferrors,
    })


def card(request, card_id):
    card = get_object_or_404(Card, pk=card_id)
    editions = get_list_or_404(CardEdition, card=card)
    return render(request, 'cardbox/card_detail.html', {
        'card': card,
        'editions': editions,
        'legality': card.get_legality(),
    })


@login_required
def collection(request, collection_id):
    collection = get_object_or_404(Collection, pk=collection_id)
    if not can_view_collection(request.user, collection):
        raise PermissionDenied

    if request.GET.get('all', '') == 'on':
        card_list = Card.objects.all()
    else:
        card_list = Card.objects.filter(editions__collection__id=collection_id)
    card_list, ferrors = _filter_cards(request, card_list)

    paginator = Paginator(card_list, 30, request=request)

    page = request.GET.get('page', 1)
    try:
        entries = paginator.page(page)
    except PageNotAnInteger:
        entries = paginator.page(1)
    except EmptyPage:
        entries = paginator.page(paginator.num_pages)

    entries.object_list = [(*card.get_count_in_collection(collection_id),
                            card) for card in entries.object_list]

    layout = request.GET.get('layout', 'list')
    if layout not in ['list', 'grid']:
        layout = 'list'

    return render(request, 'cardbox/collection.html', {
        'collection': collection,
        'entries': entries,
        'get': request.GET,
        'layout': layout,
        'ferrors': ferrors,
    })


@login_required
def edit_collection(request, collection_id=None):
    """Update or create a collection.

    :param int collection_id: (optional) The ID of the collection to
        edit.  Use ``None`` to create a new collection.

    """
    data = {}
    if collection_id is None:
        action = 'created'
        collection = Collection(owner=request.user, date_created=timezone.now())
        data['collection'] = None
    else:
        action = 'updated'
        try:
            collection = Collection.objects.get(pk=collection_id)
            if request.user != collection.owner:
                raise PermissionDenied("You are not the owner of this collection.")
            data['collection'] = collection
        except Collection.DoesNotExist:
            raise Http404('Collection not found.')

    try:
        name = request.POST['name']
        editor_list = request.POST.get('editors', '').split(',')
        viewer_list = request.POST.get('viewers', '').split(',')
    except KeyError:
        return render(request, 'cardbox/edit_collection.html', data)

    editors = []
    for editor in editor_list:
        if editor == '':
            continue
        try:
            user = User.objects.get(username=editor.strip())
            editors.append(user)
        except User.DoesNotExist:
            messages.add_message(request, messages.WARNING,
                                 'No user with name {0}.'.format(editor))
            return render(request, 'cardbox/edit_collection.html', data)

    viewers = []
    for viewer in viewer_list:
        if viewer == '':
            continue
        try:
            user = User.objects.get(username=viewer.strip())
            viewers.append(user)
        except User.DoesNotExist:
            messages.add_message(request, messages.WARNING,

cardbox/templates/cardbox/add_collection_entry.html
{% extends 'cardbox/base.html' %}

{% block content %}

<div class="page-header">
  <h1>Add cards to <a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></h1>
</div>

<div class="panel panel-primary">
  <div class="panel-body">
    <form action="{% url 'cardbox:add_collection_entry' collection.id %}" method="post">
      {% csrf_token %}
      <label for="set" class="sr-only">Set code or name</label>
      <input id="set" name="set" class="form-control" placeholder="Set code or name" required autofocus>
      <label for="number" class="sr-only">Number in set (with suffix)</label>
      <input id="number" name="number" class="form-control" placeholder="Number in set (with suffix)" required>
      <label for="count" class="sr-only">Number of copies to add</label>
      <input id="count" name="count" class="form-control" placeholder="Number of copies to add" value="1">
      <label for="fcount" class="sr-only">Number of foiled copied to add</label>
      <input id="fcount" name="fcount" class="form-control" placeholder="Number of foiled copies to add">
      <button class="btn btn-lg btn-info btn-block" type="submit" name="button" value="addanother">Save and add another</button>
      <button class="btn btn-lg btn-primary btn-block" type="submit" name="button" value="save">Save</button>
    </form>
  </div>
</div>

{% endblock %}

cardbox/templates/cardbox/card_detail.html
{% extends 'cardbox/base.html' %}

{% load staticfiles %}

{% block content %}

<div class="row">
  <div class="col-md-7">
    <div class="page-header">
      <h1>{{ card.name }} <small>{% if card.get_mana %}{{ card.get_mana }} ({{ card.cmc }}){% endif %}<br />{{ card.types }} {{ card.get_ptl }}</small></h1>
    </div>
    {% if card.rules %}
    <div class="card-rules well">{{ card.rules|linebreaks }}</div>
    {% endif  %}
    {% if card.flavour %}
    <div class="card-flavour text-muted">{{ card.flavour|linebreaks }}</div>
    {% endif %}

    <div class="content">
      <caption><h3 class="caption text-muted">legality</h3></caption>
      {% if legality.legal or legality.restricted or legality.banned %}
      {% if legality.legal %}
      <p class="text-success"><strong>Legal</strong> in {{ legality.legal|join:', ' }}</p>
      {% endif %}
      {% if legality.restricted %}
      <p class="text-warning"><strong>Restricted</strong> in {{ legality.restricted|join:', ' }}</p>
      {% endif %}
      {% if legality.banned %}
      <p class="text-danger"><strong>Banned</strong> in {{ legality.banned|join:', ' }}</p>
      {% endif %}
      {% else %}
      <p class="text-danger">This card is not legal in any format.</p>
      {% endif %}
    </div>

    {% if card.multi_type %}
    <div class="content">
      <caption><h3 class="caption text-muted">other part{{ card.multi_cards.count|pluralize }}</h3></caption>
      <ul>
        {% for mcard in card.multi_cards.all %}
        <li>
          {% if collection %}
          <a href="{% url 'cardbox:collection_card' collection.id mcard.id %}">{{ mcard.name }}</a>
          {% else %}
          <a href="{% url 'cardbox:card' mcard.id %}">{{ mcard.name }}</a>
          {% endif %}
        </li>
        {% endfor %}
      </ul>
    </div>
    {% endif %}
  </div>

  <div class="col-md-5">
    <img id="cardImage" src="{% static card.get_image_url %}" class="img-responsive" alt="{{ card.name }}">
    <p><a href="http://gatherer.wizards.com/Pages/Card/Details.aspx?multiverseid={{ card.multiverseid }}">Gatherer</a> &#9899; <a href="http://magiccards.info/query?q={{ card.name }}">MagicCardsInfo</a></p>
  </div>

  <div class="col-sm-10" id="editionTable">
    {% if collection %}
    {% include 'cardbox/collection_entry_table.html' %}
    {% else %}
    <table class="table table-striped">
      <caption><h3 class="caption text-muted">editions</h3></caption>
      {% if editions %}
      <thead>
        <tr>
          <th>Number</th>
          <th>Set</th>
          <th>Rarity</th>
          <th>Artist</th>
          <th>View</th>
        </tr>
      </thead>
      <tbody>
        {% for edition in editions %}
        <tr>
          <td>{{ edition.number }}{{ edition.number_suffix }}</td>
          <td>[{{ edition.mtgset.code }}] {{ edition.mtgset.name }}</td>
          <td>{{ edition.rarity }}</td>
          <td>{{ edition.artist }}</td>
          <td><img src="{% static 'cardbox/images/icons/image.png' %}" onclick="changeCardImage('{{ edition.mtgset.code|upper }}', '{{ edition.number }}{{ edition.number_suffix }}')"></td>
        </tr>
        {% endfor  %}
      </tbody>
      {% endif %}
    </table>
    {% endif %}
  </div>

  {% if card.rulings.all %}
  <div class="col-sm-10">
    <ul class="list-group">
      <caption><h3 class="caption text-muted">rulings</h3></caption>
      {% for ruling in card.rulings.all %}
      <li class="list-group-item"><strong>{{ ruling.date }}</strong>: {{ ruling.ruling }}</li>
      {% endfor %}
    </ul>
  </div>
  {% endif %}
</div>

{% endblock %}

{% block js %}
{% if collection %}
<script type="text/javascript">
 $(document).on("eldarion-ajax:begin", function(evt, $el) {
   if ($el.hasClass("form ajax")) {
     $('#updateStatus').removeClass("text-success text-danger").addClass("text-primary").html('updating...');
   }
 });
 $(document).on("eldarion-ajax:success", function(evt, $el, data, textStatus, jqXHR) {
   if ($el.hasClass("form ajax")) {
     $('#updateStatus').removeClass("text-danger text-primary").addClass("text-success").html('saved');
   }
 });
 $(document).on("eldarion-ajax:error", function(evt, $el, data, textStatus, jqXHR) {
   if ($el.hasClass("form ajax")) {
     $('#updateStatus').removeClass("text-success text-primary").addClass("text-danger").html('error');
   }
 });
</script>
{% endif %}
<script type="text/javascript">
 function changeCardImage(code, number) {
   url = '/static/cardbox/images/cards/' + code + '/' + number + '.jpg';
   $('#cardImage').attr('src', url);
 }
</script>
{% endblock %}

cardbox/templates/cardbox/collection.html
{% extends 'cardbox/base.html' %}

{% load staticfiles %}
{% load cardbox_tags %}

{% block content %}

<div class="row">
  <div class="col-xs-12 col-sm-8">
    <div class="page-header">
      <h1>{{ collection.name }} <small>{{ collection.date_created }}
        <div class="header-right">
          {% if request.user == collection.owner %}
          <a class="btn btn-default" href="{% url 'cardbox:edit_collection' collection.id %}" data-toggle="tooltip" data-placement="bottom" title="Settings">
            <img src="{% static 'cardbox/images/icons/settings.png' %}" alt="Settings"> Settings
          </a>
          {% endif %}
          {% if request.user == collection.owner or request.user in collection.editors.all %}
          <a class="btn btn-default" href="{% url 'cardbox:add_collection_entry' collection.id %}" data-toggle="tooltip" data-placement="bottom" title="Add cards">
            <img src="{% static 'cardbox/images/icons/add.png' %}" alt="Add card"> Add
          </a>
          {% endif %}

          <div class="btn-group" role="group" aria-label="...">
            <a class="btn btn-default{% if layout == 'list' %} active {% endif %}" role="button" href="{% append_to_get layout='list' %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="list">
              <img src="{% static 'cardbox/images/icons/list.png' %}">
            </a>
            <a class="btn btn-default{% if layout == 'grid' %} active {% endif %}" role="button" href="{% append_to_get layout='grid' %}" data-toggle="tooltip" data-placement="bottom" data-container="body" title="grid">
              <img src="{% static 'cardbox/images/icons/grid.png' %}">
            </a>
          </div>
        </div>
      </small></h1>
    </div>
    {% if layout == 'list' %}
    <table class="table table-striped">
      <thead>
        <tr>
          <th>Count</th>
          <th>Foiled</th>
          <th>Name</th>
          <th>Types</th>
          <th>P/T/L</th>
          <th>Mana</th>
        </tr>
      </thead>
      <tbody>
        {% for count, fcount, card in entries.object_list %}
        <tr>
          <td>{{ count }}</td>
          <td>{{ fcount }}</td>
          <td><a href="{% url 'cardbox:collection_card' collection.id card.id %}">{{ card.name }}</a></td>
          <td>{{ card.types }}</td>
          <td>{{ card.get_ptl }}</td>
          <td>{{ card.get_mana }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
    {% else %}
    <div class="container-fluid">
      <div class="row">
        {% for count, fcount, card in entries.object_list %}
        <div class="col-xs-6 col-md-4">
          <div>Copies: {{ count }}, Foils: {{ fcount }}</div>
          <a href="{% url 'cardbox:collection_card' collection.id card.id %}" class="thumbnail">
            <img src="{% static card.get_image_url %}" alt="{{ card.name }}">
          </a>
        </div>
        {% endfor %}
      </div>
    </div>
    {% endif %}
    {% include 'cardbox/pagination.html' with page_obj=entries %}
  </div>
  <div class="col-xs-6 col-sm-4">
    <div class="offcanvas-content-right">
      {% include 'cardbox/filter_sidebar.html' %}
    </div>
  </div>
</div>

{% endblock %}

cardbox/templates/cardbox/drawer.html
{% load staticfiles %}

<aside class="offcanvas-drawer offcanvas-drawer-left visible-xs">
  <ul class="nav navbar-nav">
    <li><h3>Navigation</h3></li>
    <li><a href="{% url 'cardbox:cards' %}">Cards</a></li>
    {% if request.user.is_authenticated %}
    <li><a href="{% url 'cardbox:logout' %}"><img src="{% static 'cardbox/images/icons/logout.png' %}" alt="Logout" title="Logout"> Logout</a></li>
    {% else %}
    <li><a href="{% url 'cardbox:login' %}"><img src="{% static 'cardbox/images/icons/login.png' %}" alt="Login" title="Login"> Login</a></li>
    {% endif %}
    {% if request.user.is_authenticated %}
    <li><h3>Collections</h3></li>
    {% if user.collection_set.all.count > 0 %}
    <li class="dropdown-header">Your collections</li>
    {% endif %}
    {% for collection in user.collection_set.all %}
    <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></li>
    {% endfor %}
    {% if user.editable_collections.count > 0 %}
    <li class="dropdown-header">Editable collections</li>
    {% endif %}
    {% for collection in user.editable_collections.all %}
    <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }} ({{ collection.owner.username }})</a></li>
    {% endfor %}
    {% if user.viewable_collections.all.count > 0 %}
    <li class="dropdown-header">Viewable collections</li>
    {% endif %}
    {% for collection in user.viewable_collections.all %}
    <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></li>
    {% endfor %}
    <li role="seperator" class="divider"></li>
    <li><a href="{% url 'cardbox:new_collection' %}">New collection</a></li>
    {% endif %}
  </ul>
</aside>
<aside clas="offcanvas-drawer offcanvas-drawer-right visible-xs"></aside>

cardbox/templates/cardbox/edit_collection.html
{% extends 'cardbox/base.html' %}

{% block content %}

<div class="page-header">
  {% if collection %}
  <h1>Edit <a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></h1>
  {% else %}
  <h1>New Collection
  {% endif %}
</div>

<div class="panel panel-primary">
  <div class="panel-body">
    {% if collection %}
    <form action="{% url 'cardbox:edit_collection' collection.id %}" method="post">
    {% else %}
    <form action="{% url 'cardbox:new_collection' %}" method="post">
    {% endif %}
      {% csrf_token %}
      <label for="name" class="sr-only">Collection name</label>
      <input id="name" name="name" class="form-control" placeholder="Collection name" value="{{ collection.name|default:'' }}" required autofocus>
      <label for="editors" class="sr-only">Editors</label>
      <input id="editors" name="editors" class="form-control" placeholder="Editors" value="{{ collection.editors.all|join:',' }}">
      <label for="viewers" class="sr-only">Viewers</label>
      <input id="viewers" name="viewers" class="form-control" placeholder="Viewers" value="{{ collection.viewers.all|join:',' }}">
      {% if collection %}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Update</button>
      {% else %}
      <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
      {% endif %}
      </form>
  </div>
</div>

{% if collection %}
<div class="panel panel-danger">
  <div class="panel-heading">
    <h3 class="panel-title">Danger Zone!</h3>
  </div>
  <div class="panel-body">
    <p>This action can not be undone!</p>
    <a href="{% url 'cardbox:delete_collection' collection.id %}">
      <button type="button" class="btn btn-danger btn-lg btn-block">Delete</button>
    </a>
  </div>
</div>
{% endif %}

{% endblock %}

cardbox/templates/cardbox/index.html
{% extends 'cardbox/base.html' %}

{% block content %}

<div class="jumbotron">
  <h1>Welcome to cardbox</h1>

  <p>This is the index page, have fun!</p>
</div>

{% endblock %}

cardbox/templates/cardbox/navbar.html
{% load staticfiles %}

<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle pull-left" data-toggle="offcanvas" data-target="left">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% if layout %}
      <button type="button" class="navbar-toggle pull-right" data-toggle="offcanvas" data-target="right">
        <span class="sr-only">Toggle filter</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      {% endif %}
      <a class="navbar-brand" href="{% url 'cardbox:index' %}">Cardbox</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li><a href="{% url 'cardbox:cards' %}">Cards</a></li>
        {% if request.user.is_authenticated %}
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Collections<span class="caret"></span></a>
          <ul class="dropdown-menu">
            {% if user.collection_set.all.count > 0 %}
            <li class="dropdown-header">Your collections</li>
            {% endif %}
            {% for collection in user.collection_set.all %}
            <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></li>
            {% endfor %}
            {% if user.editable_collections.count > 0 %}
            <li class="dropdown-header">Editable collections</li>
            {% endif %}
            {% for collection in user.editable_collections.all %}
            <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }} ({{ collection.owner.username }})</a></li>
            {% endfor %}
            {% if user.viewable_collections.all.count > 0 %}
            <li class="dropdown-header">Viewable collections</li>
            {% endif %}
            {% for collection in user.viewable_collections.all %}
            <li><a href="{% url 'cardbox:collection' collection.id %}">{{ collection.name }}</a></li>
            {% endfor %}
            <li role="seperator" class="divider"></li>
            <li><a href="{% url 'cardbox:new_collection' %}">New collection</a></li>
          </ul>
        </li>
        {% endif %}
      </ul>
      <ul class="nav navbar-nav navbar-right">
        {% if request.user.is_authenticated %}
        <li><a href="{% url 'cardbox:logout' %}"><img src="{% static 'cardbox/images/icons/logout.png' %}" alt="Logout" title="Logout"> Logout</a></li>
        {% else %}
        <li><a href="{% url 'cardbox:login' %}"><img src="{% static 'cardbox/images/icons/login.png' %}" alt="Login" title="Login"> Login</a></li>
        {% endif %}
      </ul>
    </div><!--/.navbar-collapse -->
  </div>
</nav>

cardbox/templates/cardbox/welcome.html
{% extends 'cardbox/base.html' %}

{% block content %}
Welcome, Sir!
{% endblock %}